//! Builds the Tauri-generated assets required by the desktop shell bundle.

use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

#[derive(Debug)]
struct OfficialLocaleSource {
    code: String,
}

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("cargo should provide CARGO_MANIFEST_DIR"),
    );
    let localization_root = manifest_dir.join("localizations");

    emit_rerun_if_changed(&localization_root)
        .expect("localization source tree should be watchable");

    let official_locales = collect_official_locale_sources(&localization_root)
        .expect("official localization sources should be discoverable");
    if !official_locales.iter().any(|locale| locale.code == "en") {
        panic!("official localization sources must include en/origin.json");
    }

    write_generated_localization_manifest(&manifest_dir, &official_locales)
        .expect("generated localization manifest should write");

    tauri_build::build()
}

fn emit_rerun_if_changed(path: &Path) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", path.display());

    if path.is_dir() {
        let mut entries = fs::read_dir(path)?.collect::<Result<Vec<_>, _>>()?;
        entries.sort_by(|left, right| left.path().cmp(&right.path()));

        for entry in entries {
            emit_rerun_if_changed(&entry.path())?;
        }
    }

    Ok(())
}

fn collect_official_locale_sources(
    localization_root: &Path,
) -> io::Result<Vec<OfficialLocaleSource>> {
    let mut locale_sources = Vec::new();

    let mut entries = fs::read_dir(localization_root)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by(|left, right| left.path().cmp(&right.path()));

    for entry in entries {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }

        let Some(locale_code) = path.file_name().and_then(|value| value.to_str()) else {
            continue;
        };

        let origin_path = path.join("origin.json");
        if !origin_path.is_file() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "official locale source {} is missing origin.json",
                    path.display()
                ),
            ));
        }

        locale_sources.push(OfficialLocaleSource {
            code: locale_code.to_owned(),
        });
    }

    if locale_sources.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!(
                "no official locale source directories were found under {}",
                localization_root.display()
            ),
        ));
    }

    Ok(locale_sources)
}

fn write_generated_localization_manifest(
    manifest_dir: &Path,
    official_locales: &[OfficialLocaleSource],
) -> io::Result<()> {
    let out_dir =
        PathBuf::from(env::var("OUT_DIR").expect("cargo should provide OUT_DIR for build scripts"));
    let output_path = out_dir.join("localization_manifest.rs");

    let mut generated =
        String::from("// This file is generated by build.rs. Do not edit manually.\n");

    generated.push_str("const OFFICIAL_LOCALE_CODES: &[&str] = &[\n");
    for locale in official_locales {
        generated.push_str(&format!("    {:?},\n", locale.code));
    }
    generated.push_str("];\n\n");

    generated.push_str("const EMBEDDED_LOCALIZATION_FILES: &[(&str, &str)] = &[\n");
    for locale in official_locales {
        generated.push_str(&format!(
            "    ({:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/localizations/{}/origin.json\"))),\n",
            format!("{}.json", locale.code),
            locale.code,
        ));
    }
    generated.push_str("];\n");

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let _ = manifest_dir;
    fs::write(output_path, generated)
}
