root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/server ./cmd/server"
  entrypoint = ["./tmp/server"]
  delay = 500
  exclude_dir = [".git", "data", "tmp"]
  exclude_unchanged = true
  include_ext = ["go", "json", "yaml", "yml"]
  kill_delay = "500ms"
  poll = true
  poll_interval = 500
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true