[package]
name = "desktop-shell"
autobins = false
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[[bin]]
name = "HUP"
path = "src/main.rs"

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true, features = [] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
runtime-config = { path = "../../../crates/runtime-config" }
runtime-core = { path = "../../../crates/runtime-core" }
runtime-git = { path = "../../../crates/runtime-git" }
runtime-runner = { path = "../../../crates/runtime-runner" }
runtime-store = { path = "../../../crates/runtime-store" }

[dev-dependencies]
rusqlite = { workspace = true }
