[package]
name = "runtime-bin"
autobins = false
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[[bin]]
name = "hgp-runtime"
path = "src/main.rs"

[build-dependencies]
winresource = "0.1"

[dependencies]
runtime-config = { path = "../runtime-config" }
runtime-contracts = { path = "../runtime-contracts" }
runtime-core = { path = "../runtime-core" }
runtime-git = { path = "../runtime-git" }
runtime-manifests = { path = "../runtime-manifests" }
runtime-publish = { path = "../runtime-publish" }
runtime-runner = { path = "../runtime-runner" }
runtime-store = { path = "../runtime-store" }
serde = { workspace = true }
serde_json = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
rusqlite = { workspace = true }
